### PR TITLE
211 - lex start

### LINKED ISSUE #211: Pass MF2 WG syntax tests with trailing whitespace
Currently some syntax tests
`   {{}}   `
`  .input{$x}{{}}  `
are failing with parse errors.

### PR DESCRIPTION
**Pull request by janishorsts**
* lex the start
* handle whitespaces at the beginning and the end

Fixes #211 

```
➜  parse git:(211-lex-start) ✗ benchstat a.txt b.txt
goos: darwin
goarch: arm64
pkg: go.expect.digital/mf2/parse
cpu: Apple M2 Max
                         │    a.txt    │               b.txt                │
                         │   sec/op    │   sec/op     vs base               │
ComplexMessage_String-12   3.078µ ± 1%   3.134µ ± 1%  +1.84% (p=0.000 n=10)
Lex-12                     1.503µ ± 0%   1.581µ ± 1%  +5.19% (p=0.000 n=10)
Parse-12                   3.199µ ± 1%   3.334µ ± 2%  +4.22% (p=0.000 n=10)
geomean                    2.455µ        2.547µ       +3.74%

                         │    a.txt     │                 b.txt                 │
                         │     B/op     │     B/op      vs base                 │
ComplexMessage_String-12   20.33Ki ± 0%   20.33Ki ± 0%       ~ (p=1.000 n=10) ¹
Lex-12                       528.0 ± 0%     528.0 ± 0%       ~ (p=1.000 n=10) ¹
Parse-12                   7.000Ki ± 0%   7.000Ki ± 0%       ~ (p=1.000 n=10) ¹
geomean                    4.186Ki        4.186Ki       +0.00%
¹ all samples are equal

                         │   a.txt    │                b.txt                │
                         │ allocs/op  │ allocs/op   vs base                 │
ComplexMessage_String-12   43.00 ± 0%   43.00 ± 0%       ~ (p=1.000 n=10) ¹
Lex-12                     29.00 ± 0%   29.00 ± 0%       ~ (p=1.000 n=10) ¹
Parse-12                   59.00 ± 0%   59.00 ± 0%       ~ (p=1.000 n=10) ¹
geomean                    41.90        41.90       +0.00%
¹ all samples are equal
```

### CODE REVIEW

File: parse/lex_test.go [hunk 1]
```diff
@@ -30,7 +35,7 @@ func Test_lex(t *testing.T) {
 			name:  "unescaped }",
 			input: `}`,
 			want: []item{
-				mkErr("unescaped } in pattern"),
+				mkErr(`unexpected start char "}" in message`),
```
Comment (mvilks) [inline parse/lex_test.go:38]: why "start char"?

**Review by mvilks — APPROVED** [review]
